
version: "3.5"

services:
  webpack-cli-demo:
    ports:
      - 8080:8080
    build:
      context: ../
      dockerfile: Dockerfile.dev
    container_name: "webpack-cli-demo"
    volumes:
      - ../src:/usr/src/app/src
      - ../config:/usr/src/app/config
      - ../mock:/usr/src/app/mock
