version: "3.5"

services:
  webpack-cli-demo_build:
    build: ../
    container_name: "webpack-cli-demo_build"
    volumes:
      - dist:/usr/src/app/dist

  webpack-cli-demo_web:
    image: nginx
    ports:
      - 8080:8080
    container_name: "webpack-cli-demo_web"
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist:
